### ISSUE TITLE
The property `-webkit-box-orient` seems be filtered

### ISSUE THREAD

**Issue by flyween** [leftstick/Sero-cli#3]
Multi-line text overflow displays the ellipsis

input
```
.c-tit {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  text-overflow: ellipsis;
  overflow : hidden;
}
```
output
```
.c-tit {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  text-overflow: ellipsis;
  overflow : hidden;
}
```

**Comment by leftstick** [comment]
`less-plugin-autoprefix` is used internally, see: [startwebserver](https://github.com/leftstick/Sero-cli/blob/master/bin/tasks/startwebserver/Task.js#L18-L22) .

The rule 

```
 browsers: [
    'last 5 versions'
]
```

will remove old property whenever possible, see: [autoprefix-issue](https://github.com/postcss/autoprefixer/issues/833). 

BTW, this repo is not maintained for a long time, maybe you should pick another popular tool for your work
